<?php
/**
 * Global WebP optimisation.
 *
 * Every raster image the site serves is WebP and strictly smaller than
 * TESTRO_WEBP_MAX_BYTES:
 *
 * - New media uploads are converted to WebP before WordPress stores them, and
 *   their sub-sizes are generated as WebP.
 * - Attachments whose files are not WebP (uploaded before this module, or
 *   imported without wp_handle_upload) get a "<file>.<ext>.webp" sidecar next
 *   to every file, so the original URLs keep working.
 * - Theme images under assets/images/ get a mirror under assets/images/webp/.
 * - A WP-Cron backfill processes anything still missing; the front end swaps
 *   URLs to the WebP versions (inc/image-delivery.php).
 *
 * Manual run: php bin/optimize-images.php [--force] (or `wp testro webp optimize`).
 *
 * @package TestRo
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! defined( 'TESTRO_WEBP_MAX_BYTES' ) ) {
	// Files must be strictly smaller than this (100 KB, decimal, so it also holds for 100 KiB).
	define( 'TESTRO_WEBP_MAX_BYTES', 100000 );
}
if ( ! defined( 'TESTRO_WEBP_QUALITY_MAX' ) ) {
	define( 'TESTRO_WEBP_QUALITY_MAX', 82 );
}
if ( ! defined( 'TESTRO_WEBP_QUALITY_MIN' ) ) {
	// Below this, dimensions are reduced instead of quality.
	define( 'TESTRO_WEBP_QUALITY_MIN', 50 );
}
if ( ! defined( 'TESTRO_WEBP_MAX_EDGE' ) ) {
	// Same as WordPress' big_image_size_threshold default.
	define( 'TESTRO_WEBP_MAX_EDGE', 2560 );
}

// Bump to re-process every attachment and re-encode theme WebPs generated by an older version.
define( 'TESTRO_WEBP_VERSION', '4' );
define( 'TESTRO_WEBP_META_KEY', '_testro_webp' );
define( 'TESTRO_WEBP_ASSETS_OPTION', 'testro_webp_assets' );
define( 'TESTRO_WEBP_STATE_OPTION', 'testro_webp_state' );
define( 'TESTRO_WEBP_BACKFILL_HOOK', 'testro_webp_backfill' );

/* -------------------------------------------------------------------------
 * Encoder
 * ---------------------------------------------------------------------- */

/**
 * Whether a byte count satisfies the size rule.
 *
 * @param int $bytes File size.
 * @return bool
 */
function testro_webp_fits( $bytes ) {
	return $bytes > 0 && $bytes < TESTRO_WEBP_MAX_BYTES;
}

/**
 * Whether a file exists and satisfies the size rule.
 *
 * @param string $path Absolute path.
 * @return bool
 */
function testro_webp_file_ok( $path ) {
	clearstatcache( true, $path );
	return is_file( $path ) && testro_webp_fits( (int) filesize( $path ) );
}

/**
 * Whether a GIF file is animated.
 *
 * @param string $file Absolute path.
 * @return bool
 */
function testro_is_animated_gif( $file ) {
	if ( ! is_readable( $file ) ) {
		return false;
	}

	$fh = fopen( $file, 'rb' );
	if ( ! $fh ) {
		return false;
	}

	$count = 0;
	$chunk = '';
	while ( ! feof( $fh ) && $count < 2 ) {
		$chunk .= fread( $fh, 1024 * 100 );
		$count  = preg_match_all( '/\x00\x21\xF9\x04.{4}\x00(\x2C|\x21)/s', $chunk, $m );
		if ( strlen( $chunk ) > 1024 * 1024 ) {
			break;
		}
	}
	fclose( $fh );

	return $count > 1;
}

/**
 * Whether a file is a raster image that should be served as WebP.
 *
 * Animated GIFs are skipped (converting would drop the animation).
 *
 * @param string $file Absolute path.
 * @param string $mime Optional known mime type.
 * @return bool
 */
function testro_webp_is_convertible( $file, $mime = '' ) {
	if ( ! is_file( $file ) ) {
		return false;
	}

	$real = wp_get_image_mime( $file );
	$mime = $real ? $real : $mime;

	$raster = array( 'image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/avif', 'image/heic', 'image/heif', 'image/tiff' );
	if ( ! in_array( $mime, $raster, true ) ) {
		return false;
	}

	if ( 'image/gif' === $mime && testro_is_animated_gif( $file ) ) {
		return false;
	}

	if ( 'image/webp' === $mime ) {
		$info = wp_get_webp_info( $file );
		if ( 'animated-alpha' === $info['type'] && testro_webp_is_animated( $file ) ) {
			return false;
		}
	}

	return wp_image_editor_supports( array( 'mime_type' => $mime ) );
}

/**
 * Whether a WebP file contains an animation chunk.
 *
 * @param string $file Absolute path.
 * @return bool
 */
function testro_webp_is_animated( $file ) {
	$head = (string) file_get_contents( $file, false, null, 0, 64 ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
	return false !== strpos( $head, 'ANIM' );
}

/**
 * Temp file path next to a destination (same filesystem, so rename() is atomic).
 *
 * @param string $dest Destination path.
 * @param string $ext  Extension without dot.
 * @return string
 */
function testro_webp_temp_path( $dest, $ext = 'webp' ) {
	return trailingslashit( dirname( $dest ) ) . '.testro-' . wp_generate_password( 8, false ) . '.' . $ext;
}

/**
 * Save the editor's current image as WebP at a given quality.
 *
 * @param WP_Image_Editor $editor  Editor.
 * @param int             $quality Quality 1-100.
 * @param string          $path    Output path (.webp).
 * @return int Bytes written, 0 on failure.
 */
function testro_webp_try_quality( $editor, $quality, $path ) {
	// Converting formats makes WP_Image_Editor reset quality through this filter, overriding set_quality().
	$pin = function () use ( $quality ) {
		return $quality;
	};
	add_filter( 'wp_editor_set_quality', $pin, PHP_INT_MAX );
	$editor->set_quality( $quality );
	$saved = $editor->save( $path, 'image/webp' );
	remove_filter( 'wp_editor_set_quality', $pin, PHP_INT_MAX );
	if ( is_wp_error( $saved ) ) {
		return 0;
	}
	clearstatcache( true, $path );
	return is_file( $path ) ? (int) filesize( $path ) : 0;
}

/**
 * Save the editor's current image as lossless WebP.
 *
 * WP_Image_Editor cannot request lossless output, so the frame is exported as
 * PNG and re-encoded with GD.
 *
 * @param WP_Image_Editor $editor Editor.
 * @param string          $path   Output path (.webp).
 * @return int Bytes written, 0 when unsupported or on failure.
 */
function testro_webp_try_lossless( $editor, $path ) {
	if ( ! defined( 'IMG_WEBP_LOSSLESS' ) || ! function_exists( 'imagewebp' ) || ! function_exists( 'imagecreatefrompng' ) ) {
		return 0;
	}

	$keep_png = function ( $formats ) {
		unset( $formats['image/png'] );
		return $formats;
	};
	add_filter( 'image_editor_output_format', $keep_png, PHP_INT_MAX );
	$saved = $editor->save( testro_webp_temp_path( $path, 'png' ), 'image/png' );
	remove_filter( 'image_editor_output_format', $keep_png, PHP_INT_MAX );
	if ( is_wp_error( $saved ) ) {
		return 0;
	}

	$image = imagecreatefrompng( $saved['path'] );
	@unlink( $saved['path'] ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
	if ( ! $image ) {
		return 0;
	}
	imagepalettetotruecolor( $image );
	imagealphablending( $image, false );
	imagesavealpha( $image, true );
	if ( ! imagewebp( $image, $path, IMG_WEBP_LOSSLESS ) ) {
		return 0;
	}
	clearstatcache( true, $path );
	return is_file( $path ) ? (int) filesize( $path ) : 0;
}

/**
 * Encode an image as WebP strictly under TESTRO_WEBP_MAX_BYTES.
 *
 * Keeps the original dimensions (capped at TESTRO_WEBP_MAX_EDGE) and picks the
 * highest quality between QUALITY_MIN and QUALITY_MAX that fits. Only if even
 * QUALITY_MIN is too large are the dimensions reduced, by an estimate derived
 * from the overshoot, and the quality search repeated.
 *
 * PNG/GIF sources also try lossless WebP at each size and keep it when it is
 * no larger than the lossy result. $source and $dest may be the same file.
 *
 * @param string $source Absolute source path.
 * @param string $dest   Absolute destination .webp path.
 * @return array|\WP_Error { path, width, height, quality (int|'lossless'), bytes }
 */
function testro_webp_encode( $source, $dest ) {
	if ( ! function_exists( 'wp_get_image_editor' ) ) {
		return new WP_Error( 'testro_webp_no_editor', 'Image editor unavailable.' );
	}
	if ( ! wp_mkdir_p( dirname( $dest ) ) ) {
		return new WP_Error( 'testro_webp_mkdir', 'Unable to create ' . dirname( $dest ) );
	}

	$q_max    = (int) TESTRO_WEBP_QUALITY_MAX;
	$q_min    = (int) TESTRO_WEBP_QUALITY_MIN;
	$tmp      = testro_webp_temp_path( $dest );
	$best     = testro_webp_temp_path( $dest );
	$cleanup  = array( $tmp, $best );
	$input    = $source;
	$result   = null;

	// WordPress forces lossless output when the source is a lossless WebP; decode via PNG instead.
	if ( 'image/webp' === wp_get_image_mime( $source ) ) {
		$info = wp_get_webp_info( $source );
		if ( 'lossless' === $info['type'] ) {
			$png      = testro_webp_temp_path( $dest, 'png' );
			$keep_png = function ( $formats ) {
				unset( $formats['image/png'] );
				return $formats;
			};
			add_filter( 'image_editor_output_format', $keep_png, PHP_INT_MAX );
			$editor = wp_get_image_editor( $source );
			$saved  = is_wp_error( $editor ) ? $editor : $editor->save( $png, 'image/png' );
			remove_filter( 'image_editor_output_format', $keep_png, PHP_INT_MAX );
			if ( is_wp_error( $saved ) ) {
				return $saved;
			}
			$input     = $saved['path'];
			$cleanup[] = $input;
		}
	}

	$graphic = in_array( wp_get_image_mime( $input ), array( 'image/png', 'image/gif' ), true );
	$target  = 0;
	while ( null === $result ) {
		$editor = wp_get_image_editor( $input );
		if ( is_wp_error( $editor ) ) {
			$result = $editor;
			break;
		}
		$editor->maybe_exif_rotate();

		$size = $editor->get_size();
		$long = max( (int) $size['width'], (int) $size['height'] );
		if ( ! $target ) {
			$target = min( $long, (int) TESTRO_WEBP_MAX_EDGE );
		}
		if ( $target < $long ) {
			$resized = $editor->resize( $target, $target, false );
			if ( is_wp_error( $resized ) ) {
				$result = $resized;
				break;
			}
			$size = $editor->get_size();
		} elseif ( $editor instanceof WP_Image_Editor_GD && in_array( wp_get_image_mime( $input ), array( 'image/png', 'image/gif' ), true ) ) {
			// GD cannot encode palette images as WebP; a full-frame crop yields a truecolor copy.
			$editor->crop( 0, 0, (int) $size['width'], (int) $size['height'] );
		}

		$fit_q = 0;
		$bytes = testro_webp_try_quality( $editor, $q_max, $tmp );
		if ( ! $bytes ) {
			$result = new WP_Error( 'testro_webp_encode', 'WebP encoding failed for ' . $source );
			break;
		}

		if ( testro_webp_fits( $bytes ) ) {
			$fit_q = $q_max;
			copy( $tmp, $best );
		} else {
			$min_bytes = testro_webp_try_quality( $editor, $q_min, $tmp );
			if ( testro_webp_fits( $min_bytes ) ) {
				$fit_q = $q_min;
				copy( $tmp, $best );
				$hi = $q_max;
				while ( $hi - $fit_q > 2 ) {
					$mid = (int) floor( ( $fit_q + $hi ) / 2 );
					if ( testro_webp_fits( testro_webp_try_quality( $editor, $mid, $tmp ) ) ) {
						$fit_q = $mid;
						copy( $tmp, $best );
					} else {
						$hi = $mid;
					}
				}
			}
		}

		// Flat graphics are often smaller as lossless WebP; use it when it fits and is no larger.
		if ( $graphic ) {
			clearstatcache( true, $best );
			$lossy_bytes    = $fit_q ? (int) filesize( $best ) : 0;
			$lossless_bytes = testro_webp_try_lossless( $editor, $tmp );
			if ( testro_webp_fits( $lossless_bytes ) && ( ! $fit_q || $lossless_bytes <= $lossy_bytes ) ) {
				copy( $tmp, $best );
				$fit_q = 'lossless';
			}
		}

		if ( $fit_q ) {
			if ( ! rename( $best, $dest ) ) {
				$result = new WP_Error( 'testro_webp_rename', 'Unable to write ' . $dest );
				break;
			}
			clearstatcache( true, $dest );
			$result = array(
				'path'    => $dest,
				'width'   => (int) $size['width'],
				'height'  => (int) $size['height'],
				'quality' => $fit_q,
				'bytes'   => (int) filesize( $dest ),
			);
			break;
		}

		// Even minimum quality is too big: shrink by the estimated area ratio (with headroom).
		$current = max( (int) $size['width'], (int) $size['height'] );
		$ratio   = sqrt( ( TESTRO_WEBP_MAX_BYTES * 0.9 ) / max( 1, (int) $min_bytes ) );
		$ratio   = min( 0.92, max( 0.5, $ratio ) );
		$target  = (int) floor( $current * $ratio );
		if ( $target < 16 ) {
			$result = new WP_Error( 'testro_webp_limit', 'Unable to encode ' . $source . ' under the size limit.' );
		}
	}

	foreach ( $cleanup as $file ) {
		if ( is_file( $file ) ) {
			@unlink( $file ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		}
	}

	return $result;
}

/* -------------------------------------------------------------------------
 * Media uploads
 * ---------------------------------------------------------------------- */

/**
 * Convert every uploaded raster image to an optimized WebP before WordPress
 * creates the attachment (covers media library, REST API and sideloads).
 *
 * @param array $upload Upload data (file, url, type).
 * @return array
 */
function testro_convert_upload_to_webp( $upload ) {
	if ( ! empty( $upload['error'] ) || empty( $upload['file'] ) || empty( $upload['type'] ) ) {
		return $upload;
	}

	$file = $upload['file'];
	if ( ! testro_webp_is_convertible( $file, $upload['type'] ) ) {
		return $upload;
	}

	$is_webp = 'image/webp' === wp_get_image_mime( $file );
	if ( $is_webp && testro_webp_file_ok( $file ) ) {
		$dims = wp_getimagesize( $file );
		if ( $dims && max( $dims[0], $dims[1] ) <= TESTRO_WEBP_MAX_EDGE ) {
			return $upload;
		}
	}

	$dir = dirname( $file );
	if ( $is_webp ) {
		$dest = $file;
	} else {
		// wp_unique_filename() already reserved the .webp name for this upload (jpeg/png/gif map to webp).
		$name = pathinfo( $file, PATHINFO_FILENAME ) . '.webp';
		$dest = file_exists( $dir . '/' . $name ) ? $dir . '/' . wp_unique_filename( $dir, $name ) : $dir . '/' . $name;
	}

	$result = testro_webp_encode( $file, $dest );
	if ( is_wp_error( $result ) ) {
		error_log( 'TestRo WebP upload: ' . $result->get_error_message() ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
		return $upload;
	}

	if ( $dest !== $file ) {
		wp_delete_file( $file );
	}

	$upload['file'] = $dest;
	$upload['type'] = 'image/webp';
	if ( ! empty( $upload['url'] ) ) {
		$upload['url'] = trailingslashit( dirname( $upload['url'] ) ) . wp_basename( $dest );
	}

	return $upload;
}
add_filter( 'wp_handle_upload', 'testro_convert_upload_to_webp' );

/**
 * Generate image sub-sizes as WebP.
 *
 * @param array $formats Mime map.
 * @return array
 */
function testro_image_editor_output_format( $formats ) {
	$formats['image/jpeg'] = 'image/webp';
	$formats['image/png']  = 'image/webp';
	$formats['image/gif']  = 'image/webp';
	return $formats;
}
add_filter( 'image_editor_output_format', 'testro_image_editor_output_format' );

/**
 * Default WebP quality for sub-sizes (oversized results are re-encoded afterwards).
 *
 * @param int    $quality Quality.
 * @param string $mime    Mime type.
 * @return int
 */
function testro_webp_editor_quality( $quality, $mime = '' ) {
	if ( 'image/webp' === $mime ) {
		return TESTRO_WEBP_QUALITY_MAX;
	}
	return $quality;
}
add_filter( 'wp_editor_set_quality', 'testro_webp_editor_quality', 10, 2 );

/* -------------------------------------------------------------------------
 * Attachments (new and existing)
 * ---------------------------------------------------------------------- */

/**
 * Sidecar WebP path for a non-WebP file ("photo.jpg" → "photo.jpg.webp").
 *
 * @param string $file Absolute path.
 * @return string
 */
function testro_webp_sidecar_path( $file ) {
	return $file . '.webp';
}

/**
 * Make every file of an attachment satisfy the WebP rule.
 *
 * WebP files over the limit are re-encoded in place (metadata dimensions are
 * updated if they had to shrink); other raster files get a sidecar WebP.
 *
 * @param int        $attachment_id Attachment ID.
 * @param array|null $metadata      Attachment metadata (defaults to stored metadata).
 * @param bool       $force         Re-encode sidecars that already exist.
 * @return array { metadata: array, changed: bool, errors: string[] }
 */
function testro_webp_optimize_attachment( $attachment_id, $metadata = null, $force = false ) {
	$out  = array(
		'metadata' => is_array( $metadata ) ? $metadata : wp_get_attachment_metadata( $attachment_id ),
		'changed'  => false,
		'errors'   => array(),
	);
	$file = get_attached_file( $attachment_id );
	if ( ! $file || ! is_file( $file ) || ! is_array( $out['metadata'] ) ) {
		return $out;
	}

	$meta = &$out['metadata'];
	$dir  = trailingslashit( dirname( $file ) );

	// key => absolute path; key is 'full', 'original' or a size name.
	$files = array( 'full' => $file );
	if ( ! empty( $meta['original_image'] ) ) {
		$files['original'] = $dir . $meta['original_image'];
	}
	if ( ! empty( $meta['sizes'] ) && is_array( $meta['sizes'] ) ) {
		foreach ( $meta['sizes'] as $name => $size ) {
			if ( ! empty( $size['file'] ) ) {
				$files[ 'size:' . $name ] = $dir . $size['file'];
			}
		}
	}

	$done = array();
	foreach ( $files as $key => $path ) {
		if ( isset( $done[ $path ] ) || ! testro_webp_is_convertible( $path ) ) {
			continue;
		}
		$done[ $path ] = true;

		if ( 'image/webp' === wp_get_image_mime( $path ) ) {
			if ( testro_webp_file_ok( $path ) ) {
				continue;
			}
			$result = testro_webp_encode( $path, $path );
			if ( is_wp_error( $result ) ) {
				$out['errors'][] = $result->get_error_message();
				continue;
			}
			$out['changed'] = true;
			if ( 'full' === $key ) {
				$meta['width']    = $result['width'];
				$meta['height']   = $result['height'];
				$meta['filesize'] = $result['bytes'];
			} elseif ( 0 === strpos( $key, 'size:' ) ) {
				$name                              = substr( $key, 5 );
				$meta['sizes'][ $name ]['width']    = $result['width'];
				$meta['sizes'][ $name ]['height']   = $result['height'];
				$meta['sizes'][ $name ]['filesize'] = $result['bytes'];
			}
			continue;
		}

		$sidecar = testro_webp_sidecar_path( $path );
		if ( ! $force && testro_webp_file_ok( $sidecar ) && filemtime( $sidecar ) >= filemtime( $path ) ) {
			continue;
		}
		$result = testro_webp_encode( $path, $sidecar );
		if ( is_wp_error( $result ) ) {
			$out['errors'][] = $result->get_error_message();
		}
	}

	if ( empty( $out['errors'] ) ) {
		update_post_meta( $attachment_id, TESTRO_WEBP_META_KEY, TESTRO_WEBP_VERSION );
	}

	return $out;
}

/**
 * Optimize attachment files whenever WordPress (re)generates metadata.
 *
 * @param array $metadata      Attachment metadata.
 * @param int   $attachment_id Attachment ID.
 * @return array
 */
function testro_optimize_attachment_metadata( $metadata, $attachment_id ) {
	if ( ! wp_attachment_is_image( $attachment_id ) ) {
		return $metadata;
	}
	$result = testro_webp_optimize_attachment( $attachment_id, $metadata );
	return $result['metadata'];
}
add_filter( 'wp_generate_attachment_metadata', 'testro_optimize_attachment_metadata', 20, 2 );

/**
 * Delete sidecar WebPs together with the files they belong to.
 *
 * @param string $file Path being deleted.
 * @return string
 */
function testro_webp_delete_sidecar( $file ) {
	if ( is_string( $file ) && ! preg_match( '/\.webp$/i', $file ) ) {
		$sidecar = testro_webp_sidecar_path( $file );
		if ( is_file( $sidecar ) ) {
			@unlink( $sidecar ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
		}
	}
	return $file;
}
add_filter( 'wp_delete_file', 'testro_webp_delete_sidecar' );

/**
 * Image attachments that have not been processed by the current version.
 *
 * @param int $limit Max IDs.
 * @return int[]
 */
function testro_webp_pending_attachments( $limit = 20 ) {
	$query = new WP_Query(
		array(
			'post_type'              => 'attachment',
			'post_status'            => 'inherit',
			'post_mime_type'         => array( 'image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/avif', 'image/heic', 'image/tiff' ),
			'posts_per_page'         => $limit,
			'fields'                 => 'ids',
			'orderby'                => 'ID',
			'order'                  => 'ASC',
			'no_found_rows'          => true,
			'update_post_term_cache' => false,
			'meta_query'             => array( // phpcs:ignore WordPress.DB.SlowDBQuery.slow_db_query_meta_query
				'relation' => 'OR',
				array(
					'key'     => TESTRO_WEBP_META_KEY,
					'compare' => 'NOT EXISTS',
				),
				array(
					'key'     => TESTRO_WEBP_META_KEY,
					'value'   => TESTRO_WEBP_VERSION,
					'compare' => '!=',
				),
			),
		)
	);
	return array_map( 'intval', $query->posts );
}

/* -------------------------------------------------------------------------
 * Theme images (assets/images → assets/images/webp)
 * ---------------------------------------------------------------------- */

/**
 * Theme image directories that are never converted (generated output, and
 * favicons/touch icons that platforms require as PNG).
 *
 * @return string[]
 */
function testro_webp_theme_excluded_dirs() {
	return array( 'webp', 'avif', 'icons' );
}

/**
 * WebP counterpart of a theme image, relative to assets/.
 *
 * "images/home/hero.jpg" → "images/webp/home/hero.webp". Root-level images keep
 * the historical "images/webp/<name>.webp" location.
 *
 * @param string $path Path relative to assets/ (e.g. images/home/hero.jpg).
 * @return string Relative WebP path, or '' when the path is not convertible.
 */
function testro_webp_theme_relative( $path ) {
	$path = ltrim( (string) $path, '/' );
	if ( ! preg_match( '#^images/(.+)\.(png|jpe?g|gif)$#i', $path, $m ) ) {
		return '';
	}
	$first = strtolower( strtok( $m[1], '/' ) );
	if ( false !== strpos( $m[1], '/' ) && in_array( $first, testro_webp_theme_excluded_dirs(), true ) ) {
		return '';
	}
	return 'images/webp/' . $m[1] . '.webp';
}

/**
 * All convertible theme images, relative to assets/.
 *
 * @return string[]
 */
function testro_webp_theme_sources() {
	$base = TESTRO_DIR . '/assets/images';
	if ( ! is_dir( $base ) ) {
		return array();
	}

	$sources  = array();
	$iterator = new RecursiveIteratorIterator(
		new RecursiveCallbackFilterIterator(
			new RecursiveDirectoryIterator( $base, FilesystemIterator::SKIP_DOTS ),
			function ( $item ) use ( $base ) {
				if ( $item->isDir() ) {
					return dirname( $item->getPathname() ) !== $base
						|| ! in_array( strtolower( $item->getFilename() ), testro_webp_theme_excluded_dirs(), true );
				}
				return (bool) preg_match( '/\.(png|jpe?g|gif)$/i', $item->getFilename() );
			}
		)
	);
	foreach ( $iterator as $item ) {
		$sources[] = 'images/' . ltrim( str_replace( '\\', '/', substr( $item->getPathname(), strlen( $base ) ) ), '/' );
	}
	sort( $sources );
	return $sources;
}

/**
 * Generate missing or stale WebP versions of theme images.
 *
 * An existing WebP is reused when it is under the limit and was built from the
 * current source (tracked by source hash), so nothing is re-encoded needlessly.
 * Manifest entries are { hash, v } where v is the TESTRO_WEBP_VERSION that
 * encoded the file, or 'adopted' for a valid WebP that predates the manifest.
 *
 * @param bool  $force    Re-encode everything.
 * @param float $deadline microtime(true) after which to stop (0 = no limit).
 * @return array { processed: string[], skipped: string[], errors: string[], complete: bool }
 */
function testro_webp_optimize_theme_assets( $force = false, $deadline = 0 ) {
	$manifest = get_option( TESTRO_WEBP_ASSETS_OPTION, array() );
	$manifest = is_array( $manifest ) ? $manifest : array();
	$out      = array(
		'processed' => array(),
		'skipped'   => array(),
		'errors'    => array(),
		'complete'  => true,
	);
	$targets  = array();

	foreach ( testro_webp_theme_sources() as $rel ) {
		$webp_rel = testro_webp_theme_relative( $rel );
		$source   = TESTRO_DIR . '/assets/' . $rel;
		$target   = TESTRO_DIR . '/assets/' . $webp_rel;
		if ( '' === $webp_rel || ! testro_webp_is_convertible( $source ) ) {
			continue;
		}
		if ( isset( $targets[ $webp_rel ] ) ) {
			$out['errors'][] = sprintf( '%s skipped: %s already maps to %s', $rel, $targets[ $webp_rel ], $webp_rel );
			continue;
		}
		$targets[ $webp_rel ] = $rel;

		$hash  = md5_file( $source );
		$known = isset( $manifest[ $rel ]['hash'] ) ? $manifest[ $rel ] : null;
		$fresh = $known && $known['hash'] === $hash && in_array( $known['v'], array( TESTRO_WEBP_VERSION, 'adopted' ), true );
		if ( ! $force && testro_webp_file_ok( $target ) && ( null === $known || $fresh ) ) {
			if ( null === $known ) {
				$manifest[ $rel ] = array(
					'hash' => $hash,
					'v'    => 'adopted',
				);
			}
			$out['skipped'][] = $rel;
			continue;
		}

		if ( $deadline && microtime( true ) > $deadline ) {
			$out['complete'] = false;
			break;
		}

		$result = testro_webp_encode( $source, $target );
		if ( is_wp_error( $result ) ) {
			$out['errors'][] = $rel . ': ' . $result->get_error_message();
			continue;
		}
		$manifest[ $rel ]   = array(
			'hash' => $hash,
			'v'    => TESTRO_WEBP_VERSION,
		);
		$out['processed'][] = $rel;
	}

	update_option( TESTRO_WEBP_ASSETS_OPTION, $manifest, false );
	return $out;
}

/* -------------------------------------------------------------------------
 * Backfill (WP-Cron) and manual runs
 * ---------------------------------------------------------------------- */

/**
 * Signature that changes whenever the theme or this module changes.
 *
 * @return string
 */
function testro_webp_state_signature() {
	return TESTRO_VERSION . '|' . TESTRO_WEBP_VERSION;
}

/**
 * Process theme images and pending attachments.
 *
 * @param bool  $force    Re-encode even valid existing WebPs.
 * @param float $deadline microtime(true) after which to stop (0 = run to completion).
 * @return array { theme: array, attachments: array<int, string[]>, complete: bool, failed: bool }
 */
function testro_webp_optimize_all( $force = false, $deadline = 0 ) {
	$report = array(
		'theme'       => testro_webp_optimize_theme_assets( $force, $deadline ),
		'attachments' => array(),
		'complete'    => true,
		'failed'      => false,
	);
	$report['complete'] = $report['theme']['complete'];
	$report['failed']   = ! empty( $report['theme']['errors'] );

	if ( $force ) {
		delete_post_meta_by_key( TESTRO_WEBP_META_KEY );
	}

	$failed = array();
	while ( $report['complete'] ) {
		$ids = array_diff( testro_webp_pending_attachments( 20 ), $failed );
		if ( empty( $ids ) ) {
			break;
		}
		foreach ( $ids as $id ) {
			if ( $deadline && microtime( true ) > $deadline ) {
				$report['complete'] = false;
				break;
			}
			$result = testro_webp_optimize_attachment( $id, null, $force );
			if ( $result['changed'] ) {
				wp_update_attachment_metadata( $id, $result['metadata'] );
			}
			$report['attachments'][ $id ] = $result['errors'];
			if ( ! empty( $result['errors'] ) ) {
				$failed[]         = $id;
				$report['failed'] = true;
			}
		}
	}

	// Failures are not retried on every request; the backfill handler schedules a later retry.
	if ( $report['complete'] ) {
		update_option( TESTRO_WEBP_STATE_OPTION, testro_webp_state_signature(), false );
	}

	return $report;
}

/**
 * Cron handler: work for ~20 seconds, then reschedule if anything is left
 * (soon when out of time, in an hour when some image failed).
 */
function testro_webp_run_backfill() {
	$report = testro_webp_optimize_all( false, microtime( true ) + 20 );
	if ( ! $report['complete'] ) {
		wp_schedule_single_event( time() + 30, TESTRO_WEBP_BACKFILL_HOOK );
	} elseif ( $report['failed'] ) {
		wp_schedule_single_event( time() + HOUR_IN_SECONDS, TESTRO_WEBP_BACKFILL_HOOK );
	}
}
add_action( TESTRO_WEBP_BACKFILL_HOOK, 'testro_webp_run_backfill' );

/**
 * Queue a backfill after theme updates, and re-check daily for images added
 * outside the upload flow (FTP, deploys, imports).
 */
function testro_webp_maybe_schedule() {
	if ( get_option( TESTRO_WEBP_STATE_OPTION ) !== testro_webp_state_signature() ) {
		$next = wp_next_scheduled( TESTRO_WEBP_BACKFILL_HOOK );
		if ( $next && $next > time() + MINUTE_IN_SECONDS ) {
			wp_unschedule_event( $next, TESTRO_WEBP_BACKFILL_HOOK );
			$next = false;
		}
		if ( ! $next ) {
			wp_schedule_single_event( time(), TESTRO_WEBP_BACKFILL_HOOK );
		}
	}
	if ( ! wp_next_scheduled( 'testro_webp_daily' ) ) {
		wp_schedule_event( time() + HOUR_IN_SECONDS, 'daily', 'testro_webp_daily' );
	}
}
add_action( 'init', 'testro_webp_maybe_schedule' );
add_action( 'testro_webp_daily', 'testro_webp_run_backfill' );

/**
 * Stop the daily check when the theme is switched off.
 */
function testro_webp_unschedule() {
	wp_clear_scheduled_hook( 'testro_webp_daily' );
	wp_clear_scheduled_hook( TESTRO_WEBP_BACKFILL_HOOK );
}
add_action( 'switch_theme', 'testro_webp_unschedule' );

/**
 * Every served-image candidate with the WebP file that should be delivered.
 *
 * @return array[] { source, webp, bytes, ok }
 */
function testro_webp_audit() {
	$rows = array();
	$add  = function ( $source, $webp ) use ( &$rows ) {
		clearstatcache( true, $webp );
		$bytes  = is_file( $webp ) ? (int) filesize( $webp ) : 0;
		$rows[] = array(
			'source' => $source,
			'webp'   => $webp,
			'bytes'  => $bytes,
			'ok'     => testro_webp_fits( $bytes ) && 'image/webp' === wp_get_image_mime( $webp ),
		);
	};

	foreach ( testro_webp_theme_sources() as $rel ) {
		$source = TESTRO_DIR . '/assets/' . $rel;
		if ( testro_webp_is_convertible( $source ) ) {
			$add( $source, TESTRO_DIR . '/assets/' . testro_webp_theme_relative( $rel ) );
		}
	}

	$ids = get_posts(
		array(
			'post_type'      => 'attachment',
			'post_mime_type' => 'image',
			'post_status'    => 'inherit',
			'posts_per_page' => -1,
			'fields'         => 'ids',
		)
	);
	foreach ( $ids as $id ) {
		$file = get_attached_file( $id );
		$meta = wp_get_attachment_metadata( $id );
		if ( ! $file ) {
			continue;
		}
		$paths = array( $file );
		if ( ! empty( $meta['original_image'] ) ) {
			$paths[] = dirname( $file ) . '/' . $meta['original_image'];
		}
		foreach ( ! empty( $meta['sizes'] ) ? $meta['sizes'] : array() as $size ) {
			$paths[] = dirname( $file ) . '/' . $size['file'];
		}
		foreach ( array_unique( $paths ) as $path ) {
			if ( ! testro_webp_is_convertible( $path ) ) {
				continue;
			}
			$is_webp = 'image/webp' === wp_get_image_mime( $path );
			$add( $path, $is_webp ? $path : testro_webp_sidecar_path( $path ) );
		}
	}

	return $rows;
}

if ( defined( 'WP_CLI' ) && WP_CLI ) {
	/**
	 * `wp testro webp optimize [--force]` and `wp testro webp audit`.
	 *
	 * @param array $args       Positional args.
	 * @param array $assoc_args Flags.
	 */
	WP_CLI::add_command(
		'testro webp',
		function ( $args, $assoc_args ) {
			$command = isset( $args[0] ) ? $args[0] : 'optimize';
			if ( 'optimize' === $command ) {
				$report = testro_webp_optimize_all( ! empty( $assoc_args['force'] ) );
				WP_CLI::log( sprintf( 'Theme images: %d encoded, %d already optimized.', count( $report['theme']['processed'] ), count( $report['theme']['skipped'] ) ) );
				WP_CLI::log( sprintf( 'Attachments processed: %d.', count( $report['attachments'] ) ) );
				foreach ( $report['theme']['errors'] as $error ) {
					WP_CLI::warning( $error );
				}
			}
			$bad = 0;
			foreach ( testro_webp_audit() as $row ) {
				if ( ! $row['ok'] ) {
					++$bad;
					WP_CLI::warning( 'Not optimized: ' . $row['source'] );
				}
			}
			$bad ? WP_CLI::error( $bad . ' image(s) not optimized.' ) : WP_CLI::success( 'All images are WebP under the size limit.' );
		}
	);
}
